# Site settings
title: "Ozark Overlook Ranch Blog"
description: ""
url: "http://ozarkoverlook.com"
baseurl: ""

#  Build settings
permalink: "/blog/:categories/:year/:month/:day/:title.html"
paginate_path: "/blog/page:num"
paginate: 3

gems:
    - jekyll-redirect-from
    - jekyll-paginate
